# action.yml
name: 'Run OPA Policies'
author: "Anup Gupta"
description: 'Run OPA Policies on terraform code'
inputs:
  policies_dir:
    description: 'Path where your policies are stored in the repo relative to root'
    required: false
    default: Infrastructure
  tfplan_json:
    description: 'Path to Terraform Plan Json file to evaluate with OPA'
    required: true
    default: "./tfplan.json"
  additonal_data_files:
    description: 'Comma Separated Path(s) to additional Data file(s) to be passed to OPA'
    required: false
  additonal_config_json_files:
    description: 'Comma Separated Path(s) to additional Configuration JSON file(s) to be passed to OPA'
    required: false
  debug:
    description: Enable OPA DEBUG Mode
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.policy_dir }}
    - ${{ inputs.tfplan_json }}
    - ${{ inputs.additonal_data_files }}
    - ${{ inputs.debug }}
    - ${{ inputs.additonal_config_json_files }}
outputs:
  result:
    description: 'Whether the policy checks passed of failed'
