# action.yml
name: 'Run OPA Policies'
author: "Anup Gupta"
description: 'Run OPA Policies on terraform code'
inputs:
  policies_dir:
    description: 'Path where your policies are stored in the repo relative to root'
    required: false
    default: Infrastructure
  tfplan_json:
    description: 'Path to Terraform Plan Json file to evaluate with OPA'
    required: true
    default: "./tfplan.json"
  data_files:
    description: 'Comma Separated Path(s) to additional Data file(s) to be passed to OPA'
    required: false
    default: "utils.rego"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.policy_dir }}
    - ${{ inputs.tfplan_json }}
    - ${{ inputs.data_json }}
outputs:
  result:
    description: 'Whether the policy checks passed of failed'
